#!/bin/bash
#SBATCH -A <ProjectID>          # iService Project id
#SBATCH -J ddp                # job name
#SBATCH -p gtest             # partition dev normal normal2
#SBATCH --nodes=2             # Maximum number of nodes to be allocated
#SBATCH --cpus-per-task=4     # Number of cores per MPI task
#SBATCH --ntasks-per-node=1   # Number of MPI tasks (i.e. processes)
#SBATCH --gres=gpu:2          # GPUS per node
#SBATCH -o %x_%j.out          # Path to the standard output file

export OMP_NUM_THREADS=1
export MASTER_ADDR=$(scontrol show hostnames $SLURM_JOB_NODELIST | head -n 1) 
export MASTER_PORT=$(($RANDOM % 10000 + 20000)) # random port form 20000 to 29999 

# get GPU count
IFS=',' read -ra gpu_array <<< "$SLURM_JOB_GPUS"
GPUS_PER_NODE=${#gpu_array[@]}

export SINGULARITY="singularity exec -B /work:/work --nv \
/work/u8880716/image/pytorch_24.01-py3.sif"

export LAUNCHER="torchrun \
--nnodes $SLURM_NNODES \
--nproc_per_node $GPUS_PER_NODE \
--master_addr $MASTER_ADDR \
--master_port $MASTER_PORT \
"
export TRAIN="multinode.py 10 10" # multigpu_torchrun.py multinode.py

SECONDS=0

srun --nodes=$SLURM_NNODES --ntasks=$SLURM_NNODES \
bash -c "
    CMD=\"\$SINGULARITY \$LAUNCHER --node_rank \$SLURM_NODEID \$TRAIN\"
    echo \" \$CMD \"
    exec \$CMD
    "

#srun --nodes=$SLURM_NNODES --ntasks=$SLURM_NNODES \
#bash -c "$SINGULARITY $LAUNCHER --node_rank \$SLURM_NODEID $TRAIN"
# \$SLURM_NODEID：這裡使用了跳脫字符 \$，表示這個變數要在「遠端節點執行 bash 時」才被替換，
# 這樣才能正確抓到每個節點各自的 ID。

rm *.pt
RUNTIME=$SECONDS
HOUR=$(($RUNTIME / 3600)) ;MIN=$(((RUNTIME /60)%60)) ;SEC=$((RUNTIME % 60))
echo -e "\n  Done Runtime:$HOUR:$MIN:$SEC\n"
